fn main() {
    println!(
        "cargo:rustc-env=TOKENPULSE_BUILD_TARGET={}",
        std::env::var("TARGET").expect("Cargo target")
    );
    println!("cargo:rerun-if-env-changed=TOKENPULSE_UPDATER_PUBLIC_KEY");
    if std::env::var("CARGO_CFG_TARGET_OS").ok().as_deref() == Some("windows") {
        // Cargo's tests-only flags omit the library unit-test harness. Embed its required
        // Common Controls v6 manifest, then disable linker generation for the desktop bin:
        // that bin already receives Tauri's resource.lib manifest (and icon/version data).
        println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
        println!(
            "cargo:rustc-link-arg=/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'"
        );
        println!("cargo:rustc-link-arg-bin=token-pulse-desktop=/MANIFEST:NO");
    }
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "get_app_status",
            "get_usage_revision",
            "get_update_status",
            "check_for_updates",
            "download_update",
            "install_update",
            "get_notify_integrations",
            "prepare_notify_integration",
            "apply_notify_integration",
            "release_notify_preview",
            "retire_notify_integration",
            "get_taskbar_preferences",
            "set_taskbar_preferences",
            "get_taskbar_status",
            "retry_taskbar_embed",
            "get_account_quota",
            "get_account_service_config",
            "choose_account_service",
            "cancel_account_service_selection",
            "save_account_service_config",
            "manage_account_connection",
            "refresh_account_quota",
            "get_mini_opacity",
            "get_mini_passthrough",
            "set_mini_passthrough",
            "set_mini_opacity",
            "get_recovery_shortcut",
            "set_recovery_shortcut",
            "get_mini_scope",
            "query_mini_sessions",
            "open_mini_stats",
            "get_mini_stats_request",
            "get_main_navigation",
            "get_mini_usage",
            "set_mini_scope",
            "perform_window_action",
            "mini_window_action",
            "get_sources",
            "query_diagnostics",
            "choose_source_directory",
            "manage_source",
            "start_job",
            "start_source_reread",
            "get_job",
            "list_jobs",
            "get_rebuild_status",
            "cancel_job",
            "get_context_snapshot",
            "get_dashboard_bundle",
            "get_grouped_usage",
            "get_filter_options",
            "query_sessions",
            "get_session_bundle",
            "query_turns",
            "resolve_calendar_selection",
            "get_display_settings",
            "set_display_timezone",
            "set_display_theme",
            "set_display_privacy",
            "query_usage_events",
            "close_query_snapshot",
            "get_price_rules",
            "get_price_revalue_status",
            "start_price_revalue",
            "cancel_price_revalue",
            "get_offline_price_catalog",
            "save_price_rule",
            "mutate_model_alias",
            "retire_price_rule",
        ]),
    ))
    .expect("failed to build desktop resources");
}
